apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9857da4ee34dc1378bef9a8730dc8e34ada76f30fb3ab58925ab02fc15f3b73f
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:b9d003667507f1d8c196575fb7fe8e333380cf6a0e71ff6cd04802389901d44f
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
- digest: sha256:09ed60e7070ec3dcd24aa337283646c866557078f1c15ac908647aa01181c7ad
  name: quay.io/hodeh/vote-api
  newName: quay.io/hodeh/vote-api
- digest: sha256:4c34b01f9e75e8004686c6df23e893ce277a9a1146880ba39fca4c424af91406
  name: quay.io/hodeh/vote-ui
  newName: quay.io/hodeh/vote-ui
